# Generated by Django 5.2.15 on 2026-06-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='category',
            field=models.CharField(choices=[('ai', 'AI Projects'), ('web', 'Web Apps'), ('startup', 'Startups'), ('research', 'Research'), ('other', 'Other')], default='web', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='impact',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='problem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='stack',
            field=models.JSONField(blank=True, default=list, help_text='List of strings, e.g. ["React", "Next.js", "AWS"]'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='sub',
            field=models.CharField(blank=True, help_text='Subtitle or short description', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='description',
            field=models.TextField(blank=True, help_text='General description (optional if problem/solution are used)'),
        ),
    ]
