# Generated by Django 5.2.15 on 2026-06-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deadline',
            field=models.DateField(blank=True, help_text="Overall deadline for this client's work", null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, help_text='Project deadline', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pricing',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total project price', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='pricing',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost for this task', max_digits=10, null=True),
        ),
    ]
